# Factory instance-override demo (see alu_uvm_factory_inst_override_tb.py).
# Separate sim_build dir -- see Makefile.factory_type_override's header
# comment for why.
#
# Run with: make -f Makefile.factory_inst_override

SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += $(PWD)/alu_if_and_dut.sv

TOPLEVEL = alu_dut
MODULE = alu_uvm_factory_inst_override_tb
SIM_BUILD = sim_build_factory_inst_override

include $(shell cocotb-config --makefiles)/Makefile.sim
